services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        PROKOLESO_API_TOKEN: ${PROKOLESO_API_TOKEN}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PROKOLESO_API_TOKEN=${PROKOLESO_API_TOKEN}
    stdin_open: true
    tty: true
    command: rails server -b 0.0.0.0

  # Сервис для выполнения задач rake
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        PROKOLESO_API_TOKEN: ${PROKOLESO_API_TOKEN}
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PROKOLESO_API_TOKEN=${PROKOLESO_API_TOKEN}
    command: tail -f /dev/null # Держим контейнер запущенным

volumes:
  bundle_cache:
