services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    stdin_open: true
    tty: true
    command: rails server -b 0.0.0.0

  # Сервис для выполнения задач rake
  worker:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    command: tail -f /dev/null # Держим контейнер запущенным

volumes:
  bundle_cache:
