# app/lib/tyre_constants.rb
module TyreConstants
  SEASON_ORDER = { "letnie" => 0, "vsesezonie" => 2, "zimnie" => 1 }
  HIGHLIGHT_PHRASES_RU = [
    "лучший выбор", "топ-модель сезона", "популярная модель",
    "рекомендуем к покупке", "выбор покупателей", "бестселлер",
    "идеально для вашего авто", "надёжный выбор", "хит продаж",
    "проверенное качество", "выбирают украинцы", "максимальная эффективность",
    "высокая износостойкость", "отличное сцепление с дорогой", "повышенная безопасность",
    "лучшее соотношение цена-качество", "лидер продаж", "оптимальный вариант",
    "универсальное решение", "доверие водителей", "выбор экспертов",
    "комфортное управление", "инновационная технология"
  ].freeze

  HIGHLIGHT_PHRASES_UA = [
    "найкращий вибір", "топ-модель сезону", "популярна модель", "рекомендуємо до покупки",
    "вибір покупців", "бестселер", "ідеально для вашого авто", "надійний вибір",
    "хіт продажу", "перевірена якість", "обирають українці", "максимальна ефективність",
    "висока зносостійкість", "відмінне зчеплення з дорогою", "підвищена безпека", "краща ціна-якість",
    "лідер продажів", "оптимальний варіант", "універсальне рішення", "довіра водіїв",
    "вибір експертів", "комфортне керування", "інноваційна технологія"
  ].freeze

  TEMPLATES = [
    "%{highlight}: %{season_phrase} %{brand} %{name}",
    "%{season_phrase} %{brand} %{name}",
    "%{highlight}: %{brand} %{name}",
    "%{name} %{brand}",
    "%{brand} %{name}",
    "%{brand} %{name} — %{highlight}",
    "%{brand}: %{season_phrase} %{name}"
  ].freeze

  SEASON_TEXT_VARIANTS_RU = {
    "letnie" => ["летние шины", "шины на лето", "летняя резина", "автошины летние", "летние покрышки",
                 "авторезина на лето", "летние колеса", "летняя модель"],
    "zimnie" => ["зимние шины", "резина для зимы", "зимняя автошина", "шины на зиму", "зимняя покрышка",
                 "зимняя модель", "зимние колеса"],
    "vsesezonie" => ["всесезонные шины", "резина на все сезоны", "универсальные шины", "всесезонка", "всепогодная резина"]
  }.freeze

  SEASON_TEXT_VARIANTS_UA = {
    "letnie" => [
      "літні шини", "шини на літо", "літня гума", "автошини літні", "літні покришки",
      "автогума на літо", "літні колеса", "літня модель"
    ],
    "zimnie" => [
      "зимові шини", "гума для зими", "зимова автошина", "шини на зиму", "зимова покришка",
      "зимова модель", "зимові колеса"
    ],
    "vsesezonie" => [
      "всесезонні шини", "гума на всі сезони", "універсальні шини", "всесезонка", "всепогодні шини"
    ]
  }.freeze

  SEASON_TITLES_RU = {
    "letnie" => "Летние",
    "zimnie" => "Зимние",
    "vsesezonie" => "Всесезонные"
  }.freeze

  SEASON_TITLES_UA = {
    "letnie" => "Літні",
    "zimnie" => "Зимові",
    "vsesezonie" => "Всесезонні"
  }.freeze

  TRANSLIT_EXCEPTIONS_RU = {
    "goodyear" => "Гудиер",
    "sunny" => "Санни",
    "rydanz" => "Риданз",
    "michelin" => "Мишлен",
    "continental" => "Континенталь",
    "pirelli" => "Пирелли",
    "bridgestone" => "Бриджстоун",
    "yokohama" => "Йокогама",
    "dunlop" => "Данлоп",
    "hankook" => "Ханкук",
    "nokian" => "Нокиан",
    "toyo" => "Тойо",
    "kumho" => "Кумхо",
    "nexen" => "Нексен",
    "maxxis" => "Максис",
    "triangle" => "Триангл",
    "tigar" => "Тигар",
    "premiorri" => "Премиорри",
    "matador" => "Матадор",
    "gislaved" => "Гиславед",
    "sava" => "Сава",
    "barum" => "Барум",
    "kleber" => "Клебер",
    "falken" => "Фалкен",
    "bfgoodrich" => "БФ Гудрич",
    "firestone" => "Фаерстоун",
    "semperit" => "Семперит",
    "kapsen" => "Капсен",
    "doublestar" => "Даблстар",
    "aurora" => "Аврора",
    "cordiant" => "Кордиант",
    "viatti" => "Виатти",
    "roadstone" => "Роудстоун",
    "nordman" => "Нордман",
    "vredestein" => "Вредештейн",
    "zeetex" => "Зитекс",
    "giti" => "Гити",
    "assurance" => "Асшуренс",
    "ultragrip" => "Ультрагрип",
    "icecontact" => "АйсКонтакт",
    "blizzak" => "Близзак",
    "sportcontact" => "СпортКонтакт",
    "primacy" => "Примаси",
    "pilot" => "Пилот",
    "energy" => "Энерджи",
    "premiumcontact" => "премиумконтакт",
    "cargospeedevo" => "Каргоспидево",
    "cargo" => "Карго",
    "high" => "Хай",
    "performance" => "Перфоманс",
    "competus" => "Компетус",
    "icehawke" => "Айсхавк",
    "wintercraft" => "Винтеркрафт",
    "craft" => "Крафт",
    "wintercontact" => "винтерконтакт",
    "icept" => "АйЦепт",
    "incurro" => "Инкурро",
    "hakkapeliitta" => "хаккапелита",
    "comfort" => "комфорт",
    "ultrac" => "ультрак",
    "icemax" => "АйсМакс",
    "ice" => "Айс",
    "contiwintcont" => "контивинтерконтакт",
    "contivikingcontact" => "контивикингконтакт",
    "conti" => "конти",
    "roadhawk" => "роадхавк",
    "country" => "кантри",
    "snow" => "сноу",
    "all" => "Ол",
    "hakka" => "хакка",
    "black" => "блек",
    "weather" => "везер",
    "prime" => "прайм",
    "himalaya" => "гималая",
    "cruiser" => "круйзер",
    "icedefensor" => "айсдефензор",
    "defensor" => "дефензор",
    "speed" => "спид",
    "colo" => "коло",
    "intensa" => "интенза",
    "premiere" => "примьер",
    "eagle" => "игл",
    "asymmetric" => "асиметрик",
    "summer" => "самер",
    "advantage" => "адвантаж",
    "blue" => "блю",
    "hd" => "hd",
    "plus" => "плюс",
    "winspike" => "винспайк",
    "spike" => "спайк",
    "eurofrost" => "еврофрост",
    "luxury" => "люксори",
    "saloon" => "салун",
    "contisportcontact" => "контиспортконтакт",
    "comfotrmax" => "комфортмакс",
    "scorpion" => "скорпион",
    "arctic" => "арктик",
    "contiwintercontact" => "контивинтерконтакт",
    "wintrac" => "винтрак",
    "dynaxer" => "дунаксер",
    "vector" => "вектор",
    "snowshoes" => "сноушуз",
    "season" => "сизон",
    "seasons" => "сизонс",
    "ecsta" => "экста",
    "hectorra" => "хектора",
    "kinergy" => "кинержи",
    "eco" => "эко",
    "driveways" => "драйв вейс",
    "nordicca" => "нордика",
    "nordica" => "нордика",
    "quartaris" => "квартарис",
    "latitude" => "латитюд",
    "cross" => "кросс",
    "car" => "кар",
    "dynapro" => "дунапро",
    "crugen" => "круген",
    "ecopia" => "экопия",
    "quadraxer" => "квадраксер",
    "alpine" => "Альпин",
    "contiecocontact" => "контиэкоконтакт",
    "control" => "контрол",
    "drive" => "драйв", # https://prokoleso.ua/shiny/pirelli/powergy/
    "4seasons" => "4сизонс",
    "powergy" => "поверджи",
    "classe" => "класс",
    "sportcontrol" => "спортконтрол",
    "contiwintcontact" => "контивинтерконтакт",
    "protech" => "протеч",
    "climate" => "климат",
    "snoways" => "снов вейс",
    "crossclimate" => "кроссклимат",
    "sportcontact" => "спортконтакт",
    "contact" => "контакт",
    "ecocontact" => "экоконтакт",
    "iii" => "III",
    "winterking" => "винтеркинг",
    "prtech" => "PRTECH",
    "alpin" => "Альпин"
  }.freeze

  TRANSLIT_EXCEPTIONS_UA = {
    "goodyear" => "Гудієр",
    "sunny" => "Санні",
    "rydanz" => "Ріданз",
    "michelin" => "Мішлен",
    "continental" => "Континенталь",
    "pirelli" => "Піреллі",
    "bridgestone" => "Бріджстоун",
    "yokohama" => "Йокогама",
    "dunlop" => "Данлоп",
    "hankook" => "Ханкук",
    "nokian" => "Нокіан",
    "toyo" => "Тойо",
    "kumho" => "Кумхо",
    "nexen" => "Нексен",
    "maxxis" => "Максіс",
    "triangle" => "Тріангл",
    "tigar" => "Тігар",
    "premiorri" => "Преміоррі",
    "matador" => "Матадор",
    "gislaved" => "Гіславед",
    "sava" => "Сава",
    "barum" => "Барум",
    "kleber" => "Клебер",
    "falken" => "Фалкен",
    "bfgoodrich" => "БФГудріч",
    "firestone" => "Фаєрстоун",
    "semperit" => "Семперіт",
    "kapsen" => "Капсен",
    "doublestar" => "Даблстар",
    "aurora" => "Аврора",
    "cordiant" => "Кордіант",
    "viatti" => "Віатті",
    "roadstone" => "Роудстоун",
    "nordman" => "Нордман",
    "vredestein" => "Вредештейн",
    "zeetex" => "Зітекс",
    "giti" => "Ґіті",
    "assurance" => "Ашуренс",
    "ultragrip" => "Ультрагріп",
    "icecontact" => "АйсКонтакт",
    "blizzak" => "Бліззак",
    "sportcontact" => "СпортКонтакт",
    "primacy" => "Прімасі",
    "pilot" => "Пілот",
    "energy" => "Енерджі",
    "premiumcontact" => "преміумконтакт",
    "cargospeedevo" => "каргоспідево",
    "cargo" => "карго",
    "high" => "хай",
    "performance" => "перформанс",
    "competus" => "компетус",
    "icehawke" => "айсхавк",
    "wintercraft" => "вінтеркрафт",
    "craft" => "крафт",
    "wintercontact" => "вінтерконтакт",
    "icept" => "АйЦепт",
    "incurro" => "Інкурро",
    "hakkapeliitta" => "хаккапеліта",
    "comfort" => "комфорт",
    "ultrac" => "ультрак",
    "icemax" => "АйсМакс",
    "ice" => "Айс",
    "contiwintcont" => "контивінтерконтакт",
    "contivikingcontact" => "контивікінгконтакт",
    "conti" => "конті",
    "roadhawk" => "роадхоук",
    "country" => "кантрі",
    "snow" => "сноу",
    "all" => "Ол",
    "hakka" => "хакка",
    "black" => "блек",
    "weather" => "везер",
    "prime" => "прайм",
    "himalaya" => "гімалая",
    "cruiser" => "крузер",
    "icedefensor" => "айсдефенсор",
    "defensor" => "дефенсор",
    "speed" => "спід",
    "colo" => "коло",
    "intensa" => "інтенза",
    "premiere" => "прим'єр",
    "eagle" => "ігл",
    "asymmetric" => "асиметрік",
    "summer" => "самер",
    "advantage" => "адвантаж",
    "blue" => "блю",
    "hd" => "hd",
    "plus" => "плюс",
    "winspike" => "винспайк",
    "spike" => "спайк",
    "eurofrost" => "єврофрост",
    "luxury" => "люксорі",
    "saloon" => "салун",
    "contisportcontact" => "контиспортконтакт",
    "comfotrmax" => "комфортмакс",
    "scorpion" => "скорпіон",
    "arctic" => "арктик",
    "contiwintercontact" => "контивінтерконтакт",
    "wintrac" => "вінтрак",
    "dynaxer" => "дунаксер",
    "vector" => "вектор",
    "snowshoes" => "сноушуз",
    "season" => "сезон",
    "seasons" => "сезонз",
    "ecsta" => "екста",
    "hectorra" => "хектора",
    "kinergy" => "кінерджі",
    "eco" => "еко",
    "driveways" => "драйввейс",
    "nordicca" => "нордіка",
    "nordica" => "нордіка",
    "quartaris" => "квартарис",
    "latitude" => "латітуда",
    "cross" => "кросс",
    "car" => "кар",
    "dynapro" => "дунапро",
    "crugen" => "круген",
    "ecopia" => "екопія",
    "quadraxer" => "квадраксер",
    "alpine" => "Альпін",
    "contiecocontact" => "контиекоконтакт",
    "control" => "контрол",
    "drive" => "драйв",
    "4seasons" => "4сезонз",
    "powergy" => "поверджі",
    "classe" => "клас",
    "sportcontrol" => "спортконтрол",
    "contiwintcontact" => "контивінтерконтакт",
    "protech" => "протеч",
    "climate" => "клімат",
    "snoways" => "сноу вейс",
    "crossclimate" => "кроссклімат",
    "sportcontact" => "спортконтакт",
    "ecocontact" => "экоконтакт",
    "contact" => "контакт",
    "iii" => "III",
    "winterking" => "вінтеркінг",
    "prtech" => "PRTECH",
    "alpin" => "Альпін"
  }.freeze

  TRANSLIT_MAP_RU = {
    'a' => 'а', 'b' => 'б', 'c' => 'ц', 'd' => 'д', 'e' => 'е', 'f' => 'ф', 'g' => 'г', 'h' => 'х', 'i' => 'и',
    'j' => 'ж', 'k' => 'к', 'l' => 'л', 'm' => 'м', 'n' => 'н', 'o' => 'о', 'p' => 'п', 'q' => 'к', 'r' => 'р',
    's' => 'с', 't' => 'т', 'u' => 'у', 'v' => 'в', 'w' => 'в', 'x' => 'кс', 'y' => 'ы', 'z' => 'з'
  }

  TRANSLIT_MAP_UA = {
    'a' => 'а', 'b' => 'б', 'c' => 'ц', 'd' => 'д', 'e' => 'е', 'f' => 'ф', 'g' => 'г', 'h' => 'г', 'i' => 'і',
    'j' => 'ж', 'k' => 'к', 'l' => 'л', 'm' => 'м', 'n' => 'н', 'o' => 'о', 'p' => 'п', 'q' => 'к', 'r' => 'р',
    's' => 'с', 't' => 'т', 'u' => 'у', 'v' => 'в', 'w' => 'в', 'x' => 'кс', 'y' => 'и', 'z' => 'з'
  }

  def self.season_variants(language)
    language.to_s.downcase == "ua" ? SEASON_TEXT_VARIANTS_UA : SEASON_TEXT_VARIANTS_RU
  end

  def self.highlight_phrases(language)
    language.to_s.downcase == "ua" ? HIGHLIGHT_PHRASES_UA : HIGHLIGHT_PHRASES_RU
  end

  def self.season_titles(language)
    language.to_s.downcase == "ua" ? SEASON_TITLES_UA : SEASON_TITLES_RU
  end
end
